version: "3.1"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: ai
      TZ: America/Toronto
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - 5555:5432
    networks:
      - xbase

  ai_migrate:
    build:
      context: .
      target: migrate
    depends_on:
      - postgres
    networks:
      - xbase
    env_file:
      - app.env

  ai_svc:
    build:
      context: .
      target: api
    depends_on:
      - postgres
      - ai_migrate
    ports:
      - 5052:5052
    networks:
      - xbase
    env_file:
      - app.env

networks:
  xbase:
    driver: bridge

volumes:
  db_data:
    driver: local
    name: ai_db_data
